version: '2'
services:
    experimentmanager-app:
        image: experimentmanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://experimentmanager-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=experimentManager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    experimentmanager-mongodb:
        extends:
            file: mongodb.yml
            service: experimentmanager-mongodb
